/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class TelaLogin extends javax.swing.JFrame {

    private TelaPrincipal TelaPrincipal;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonSair = new javax.swing.JButton();
        jButtonAcessar = new javax.swing.JButton();
        jLabelAvaliaçãoFisioterapeutica = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1200));
        getContentPane().setLayout(null);

        jLabelUsuario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(140, 270, 70, 20);
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(220, 270, 250, 30);

        jLabelSenha.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(140, 300, 80, 40);
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(220, 310, 250, 30);

        jButtonSair.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(330, 360, 90, 27);

        jButtonAcessar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonAcessar.setText("Acessar");
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcessar);
        jButtonAcessar.setBounds(190, 360, 90, 27);

        jLabelAvaliaçãoFisioterapeutica.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        jLabelAvaliaçãoFisioterapeutica.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAvaliaçãoFisioterapeutica.setText("Avaliação Fisioterapeutica");
        getContentPane().add(jLabelAvaliaçãoFisioterapeutica);
        jLabelAvaliaçãoFisioterapeutica.setBounds(80, 20, 480, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logotipo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 60, 310, 230);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo12.jpg"))); // NOI18N
        jLabelFundo.setText("jLabel1");
        jLabelFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFundo.setPreferredSize(new java.awt.Dimension(1920, 1200));
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-410, -40, 1050, 470);

        setSize(new java.awt.Dimension(655, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
        if(jTextFieldUsuario.getText().equals("Admin")&&jPasswordFieldSenha.getText().equals("Admin")) {
        TelaPrincipal tela= new TelaPrincipal (); 
        tela.setVisible (true);
        dispose ();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Senha ou Usuário Invalidos!");
        }
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit (0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAvaliaçãoFisioterapeutica;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
